def get_predictors_info():
    bio_info = {
        'roughness_std3x3':                 {'title': "Пересечённость рельефа (стандартное отклонение на сетке 3х3 км)", 'unit': '', 'scale': 1, 'diff': 0},
        'slope_deg':                        {'title': "Уклон рельефа на заданном шаге модели", 'unit': '', 'scale': 1, 'diff': 0},
        'distance_to_cities':               {'title': "Расстояние до городской застройки", 'unit': '', 'scale': 1, 'diff': 0},
        'distance_to_water':                {'title': "Расстояние до водоёмов", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_elev':                   {'title': "WC ELEV: Высота над уровнем моря", 'unit': '', 'scale': 1, 'diff': 0},
        
        'wc2.1_30s_bio_1':                  {'title': "WC BIO1: Среднегодовая температура (Mean annual temperature)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_2':                  {'title': "WC BIO2: Среднегодовая суточная температурная амплитуда (Mean diurnal range)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_3':                  {'title': "WC BIO3: Изотермичность/сезонность температуры (Temperature seasonality, 100 * BIO2 / BIO7)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_4':                  {'title': "WC BIO4: Сезонность температуры (Temperature seasonality, стандартное отклонение * 100)", 'unit': '', 'scale': 1, 'diff': 0}, 
        'wc2.1_30s_bio_5':                  {'title': "WC BIO5: Средняя максимальная температура самого теплого месяца (Max temperature of warmest month)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_6':                  {'title': "WC BIO6: Средняя минимальная температура самого холодного месяца (Min temperature of coldest month)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_7':                  {'title': "WC BIO7: Годовая температурная амплитуда (Annual temperature range, BIO5 - BIO6)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_8':                  {'title': "WC BIO8: Средняя температура самого влажного квартала (Mean temperature of wettest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_9':                  {'title': "WC BIO9: Средняя температура самого сухого квартала (Mean temperature of driest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_10':                 {'title': "WC BIO10: Средняя температура самого теплого квартала (Mean temperature of warmest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_11':                 {'title': "WC BIO11: Средняя температура самого холодного квартала (Mean temperature of coldest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_12':                 {'title': "WC BIO12: Годовое количество осадков (Annual precipitation)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_13':                 {'title': "WC BIO13: Количество осадков самого влажного месяца (Precipitation of wettest month)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_14':                 {'title': "WC BIO14: Количество осадков самого сухого месяца (Precipitation of driest month)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_15':                 {'title': "WC BIO15: Сезонность осадков (Precipitation seasonality)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_16':                 {'title': "WC BIO16: Количество осадков самого влажного квартала (Precipitation of wettest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_17':                 {'title': "WC BIO17: Количество осадков самого сухого квартала (Precipitation of driest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_18':                 {'title': "WC BIO18: Количество осадков самого теплого квартала (Precipitation of warmest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        'wc2.1_30s_bio_19':                 {'title': "WC BIO19: Количество осадков самого холодного квартала (Precipitation of coldest quarter)", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_bio01_1981-2010_V.2.1':     {'title': "CHELSA BIO1: Среднегодовая температура (Mean annual temperature), х10 К", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio02_1981-2010_V.2.1':     {'title': "CHELSA BIO2: Среднегодовая суточная температурная амплитуда (Mean diurnal range), х10", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio03_1981-2010_V.2.1':     {'title': "CHELSA BIO3: Изотермичность/сезонность температуры (Temperature seasonality, 100 * BIO2 / BIO7), х10", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio04_1981-2010_V.2.1':     {'title': "CHELSA BIO4: Сезонность температуры (Temperature seasonality, стандартное отклонение * 100), х10", 'unit': '', 'scale': 1, 'diff': 0}, 
        'CHELSA_bio05_1981-2010_V.2.1':     {'title': "CHELSA BIO5: Средняя максимальная температура самого теплого месяца (Max temperature of warmest month), х10 К", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio06_1981-2010_V.2.1':     {'title': "CHELSA BIO6: Средняя минимальная температура самого холодного месяца (Min temperature of coldest month), х10 К", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio07_1981-2010_V.2.1':     {'title': "CHELSA BIO7: Годовая температурная амплитуда (Annual temperature range, BIO5 - BIO6), х10", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio08_1981-2010_V.2.1':     {'title': "CHELSA BIO8: Средняя температура самого влажного квартала (Mean temperature of wettest quarter), х10 К", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio09_1981-2010_V.2.1':     {'title': "CHELSA BIO9: Средняя температура самого сухого квартала (Mean temperature of driest quarter), х10 К", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio10_1981-2010_V.2.1':     {'title': "CHELSA BIO10: Средняя температура самого теплого квартала (Mean temperature of warmest quarter), х10 К", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio11_1981-2010_V.2.1':     {'title': "CHELSA BIO11: Средняя температура самого холодного квартала (Mean temperature of coldest quarter), х10 К", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio12_1981-2010_V.2.1':     {'title': "CHELSA BIO12: Годовое количество осадков (Annual precipitation), мм", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio13_1981-2010_V.2.1':     {'title': "CHELSA BIO13: Количество осадков самого влажного месяца (Precipitation of wettest month), мм", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio14_1981-2010_V.2.1':     {'title': "CHELSA BIO14: Количество осадков самого сухого месяца (Precipitation of driest month), мм", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio15_1981-2010_V.2.1':     {'title': "CHELSA BIO15: Сезонность осадков (Precipitation seasonality)", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio16_1981-2010_V.2.1':     {'title': "CHELSA BIO16: Количество осадков самого влажного квартала (Precipitation of wettest quarter), мм", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio17_1981-2010_V.2.1':     {'title': "CHELSA BIO17: Количество осадков самого сухого квартала (Precipitation of driest quarter), мм", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio18_1981-2010_V.2.1':     {'title': "CHELSA BIO18: Количество осадков самого теплого квартала (Precipitation of warmest quarter), мм", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_bio19_1981-2010_V.2.1':     {'title': "CHELSA BIO19: Количество осадков самого холодного квартала (Precipitation of coldest quarter), мм", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_cmimean_1981-2010_V.2.1':   {'title': "CHELSA CMI MEAN: Средний месячный индекс влажности климата за 1 год, х0.1 кг/кв.м.*мес", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_cmimin_1981-2010_V.2.1':    {'title': "CHELSA CMI MIN: Индекс влажности климата месяца с наибольшим дефицитом осадков, х0.1 кг/кв.м.*мес", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_cmimax_1981-2010_V.2.1':    {'title': "CHELSA CMI MAX: Индекс влажности климата месяца с наибольшим избытком осадков, х0.1 кг/кв.м.*мес", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_cmirange_1981-2010_V.2.1':  {'title': "CHELSA CMI RANGE: Разница CHELSA CMI MAX-CHELSA CMI MIN, х0.1 кг/кв.м.*мес", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_cltmean_1981-2010_V.2.1':   {'title': "CHELSA CLT MEAN: Средний процент общей облачности, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_cltmin_1981-2010_V.2.1':    {'title': "CHELSA CLT MIN: Процент общей облачности наименее облачного месяца, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_cltmax_1981-2010_V.2.1':    {'title': "CHELSA CLT MAX: Процент общей облачности наиболее облачного месяца, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_cltrange_1981-2010_V.2.1':  {'title': "CHELSA CLT RANGE: Разница CHELSA CLT MAX - CHELSA CLT MIN, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_hursmean_1981-2010_V.2.1':  {'title': "CHELSA HURS MEAN: Средняя относительная влажность у поверхности, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_hursmin_1981-2010_V.2.1':   {'title': "CHELSA HURS MIN: Средняя относительная влажность у поверхности наименее влажного месяца, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_hursmax_1981-2010_V.2.1':   {'title': "CHELSA HURS MAX: Средняя относительная влажность у поверхности наиболее влажного месяца, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_hursrange_1981-2010_V.2.1': {'title': "CHELSA HURS RANGE: Разница CHELSA HURS MAX и CHELSA HURS MIN, х0.01%", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_fcf_1981-2010_V.2.1':       {'title': "CHELSA FCF: Количество переходов через ноль (замерзание-оттаивание) в год", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_fgd_1981-2010_V.2.1':       {'title': "CHELSA FGD: Юлианский день, отмечающий первое наступление условий для вегетационного периода", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gdd0_1981-2010_V.2.1':      {'title': "CHELSA GDD0: Сумма среднесуточных температур выше 0 °C, накопленная за год, х0.1°C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gdd5_1981-2010_V.2.1':      {'title': "CHELSA GDD5: Сумма среднесуточных температур выше 5 °C, накопленная за год, х0.1°C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gdd10_1981-2010_V.2.1':     {'title': "CHELSA GDD10: Сумма среднесуточных температур выше 10 °C, накопленная за год, х0.1°C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gdgfgd5_1981-2010_V.2.1':   {'title': "CHELSA GDG FGD5: Юлианский день первого наступления среднесуточной температуры выше 5 °C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gdgfgd10_1981-2010_V.2.1':  {'title': "CHELSA GDG FGD10: Юлианский день первого наступления среднесуточной температуры выше 10 °C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gddlgd0_1981-2010_V.2.1':   {'title': "CHELSA GDG LGD10: Юлианский день последнего наступления среднесуточной температуры выше 10 °C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gddlgd10_1981-2010_V.2.1':  {'title': "CHELSA GDG LGD5: Юлианский день последнего наступления среднесуточной температуры выше 5 °C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gddlgd5_1981-2010_V.2.1':   {'title': "CHELSA GDG LGD0: Юлианский день последнего наступления среднесуточной температуры выше 0 °C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gsl_1981-2010_V.2.1':       {'title': "CHELSA GSL: Количество дней между первым и последним наступлением условий для вегетационного периода", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gsp_1981-2010_V.2.1':       {'title': "CHELSA GSP: Общее количество осадков, накопленное за период вегетационного сезона, х0.1 кг/кв.м", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_gst_1981-2010_V.2.1':       {'title': "CHELSA GST: Среднесуточная средняя температура за все дни вегетационного периода, х0.1°C", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_petmean_1981-2010_V.2.1':   {'title': "CHELSA PET MEAN: Минимальная месячная потенциальная эвапотранспирация, х0.01", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_petmin_1981-2010_V.2.1':    {'title': "CHELSA PET MIN: Средняя месячная потенциальная эвапотранспирация, х0.01", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_petmax_1981-2010_V.2.1':    {'title': "CHELSA PET MAX: Максимальная месячная потенциальная эвапотранспирация, х0.01", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_petrange_1981-2010_V.2.1':  {'title': "CHELSA PET RANGE: Годовой диапазон месячной потенциальной эвапотранспирации, х0.01", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_rsdsmean_1981-2010_V.2.1':  {'title': "CHELSA RSDS MEAN: Минимальный месячный поток коротковолновой радиации, х0.001", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_rsdsmin_1981-2010_V.2.1':   {'title': "CHELSA RSDS MIN: Средний месячный поток коротковолновой радиации, х0.001", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_rsdsmax_1981-2010_V.2.1':   {'title': "CHELSA RSDS MAX: Максимальный месячный поток коротковолновой радиации, х0.001", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_rsdsrange_1981-2010_V.2.1': {'title': "CHELSA RSDS RANGE: Годовой диапазон месячного потока коротковолновой радиации, х0.001", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_vpdmean_1981-2010_V.2.1':   {'title': "CHELSA VPD MEAN: Средний месячный дефицит давления водяного пара, х0.1 Па", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_vpdmin_1981-2010_V.2.1':    {'title': "CHELSA VPD MIN: Минимальный месячный дефицит давления водяного пара, х0.1 Па", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_vpdmax_1981-2010_V.2.1':    {'title': "CHELSA VPD MAX: Максимальный месячный дефицит давления водяного пара, х0.1 Па", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_vpdrange_1981-2010_V.2.1':  {'title': "CHELSA VPD RANGE: Годовой диапазон месячного дефицита давления водяного пара, х0.1 Па", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_sfcWindmean_1981-2010_V.2.1':{'title': "CHELSA SFCW MEAN: Минимальная месячная скорость ветра у поверхности, х0.001 м/с", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_sfcWindmin_1981-2010_V.2.1': {'title': "CHELSA SFCW MIN: Средняя месячная скорость ветра у поверхности, х0.001 м/с", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_sfcWindmax_1981-2010_V.2.1': {'title': "CHELSA SFCW MAX: Максимальная месячная скорость ветра у поверхности, х0.001 м/с", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_sfcWindrange_1981-2010_V.2.1':{'title': "CHELSA SFCW RANGE: Годовой диапазон месячной скорости ветра у поверхности, х0.001 м/с", 'unit': '', 'scale': 1, 'diff': 0},
        
        'CHELSA_lgd_1981-2010_V.2.1':       {'title': "CHELSA LGD: Последний день вегетационного периода", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_ngd0_1981-2010_V.2.1':      {'title': "CHELSA NGD0: Количество дней вегетации с температурой > 0°C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_ngd5_1981-2010_V.2.1':      {'title': "CHELSA NGD5: Количество дней вегетации с температурой > 5°C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_ngd10_1981-2010_V.2.1':     {'title': "CHELSA NGD10: Количество дней вегетации с температурой > 10°C", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_npp_1981-2010_V.2.1':       {'title': "CHELSA NPP: Чистая первичная продуктивность (UNESCO, VIII, 2:5-10), х0.1", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_scd_1981-2010_V.2.1':       {'title': "CHELSA SCD: Количество дней снежного покрова", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_swb_1981-2010_V.2.1':       {'title': "CHELSA SWB: Водный баланс участка", 'unit': '', 'scale': 1, 'diff': 0},
        'CHELSA_swe_1981-2010_V.2.1':       {'title': "CHELSA SWE: Эквивалент водяного содержания снега, х0.1 кг/кв.м.*год", 'unit': '', 'scale': 1, 'diff': 0},
        
        'Consensus_reduced_class_1':        {'title': "EE CLC1: Вечнозелёные/Листопадные хвойные деревья (Evergreen/Deciduous Needleleaf Trees)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_2':        {'title': "EE CLC2: Вечнозелёные широколистные деревья (Evergreen Broadleaf Trees)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_3':        {'title': "EE CLC3: Листопадные широколистные деревья (Deciduous Broadleaf Trees)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_4':        {'title': "EE CLC4: Смешанные/Другие деревья (Mixed/Other Trees)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_5':        {'title': "EE CLC5: Кустарники (Shrubs)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_6':        {'title': "EE CLC6: Травянистая растительность (Herbaceous Vegetation)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_7':        {'title': "EE CLC7: Культивируемая и управляемая растительность (Cultivated and Managed Vegetation)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_8':        {'title': "EE CLC8: Регулярно затопляемая растительность (Regularly Flooded Vegetation)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_9':        {'title': "EE CLC9: Городская/Застроенная территория (Urban/Built-up)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_10':       {'title': "EE CLC10: Снег/Лёд (Snow/Ice)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_11':       {'title': "EE CLC11: Голые земли / Бесплодные земли (Barren)", 'unit': '', 'scale': 1, 'diff': 0},
        'Consensus_reduced_class_12':       {'title': "EE CLC12: Открытые водные пространства (Open Water)", 'unit': '', 'scale': 1, 'diff': 0},
    
        'ENVIREM_thermicityIndex':          {'title': "ENVIREM: Компенсированный индекс термичности", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_monthCountByTemp10':       {'title': "ENVIREM: Количество месяцев со средней температурой выше 10 гр.", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_minTempWarmest':           {'title': "ENVIREM: Минимальная температура самого теплого месяца, x10", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_maxTempColdest':           {'title': "ENVIREM: Максимальная температура самого холодного месяца, x10", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_growingDegDays5':          {'title': "ENVIREM: Сумма средних месячных температур для месяцев со средней температурой выше 5°, умноженная на количество дней", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_growingDegDays0':          {'title': "ENVIREM: Сумма средних месячных температур для месяцев со средней температурой выше 0°, умноженная на количество дней", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_embergerQ':                {'title': "ENVIREM: Эмбержеровский плювиотермический коэффициент", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_continentality':           {'title': "ENVIREM: Континентальность (средняя температура самого теплого месяца минус средняя температура самого холодного месяца)", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_climaticMoistureIndex':    {'title': "ENVIREM: Климатический индекс влажности (показатель относительной влажности и сухости)", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_aridityIndexThornthwaite': {'title': "ENVIREM: Индекс аридности Торнтвейта (индекс степени водного дефицита)", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_PETWettestQuarter':        {'title': "ENVIREM: Среднемесячная потенциальная эвапотранспирация самого влажного квартала", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_PETWarmestQuarter':        {'title': "ENVIREM: Среднемесячная потенциальная эвапотранспирация самого теплого квартала", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_PETseasonality':           {'title': "ENVIREM: Сезонность потенциальной эвапотранспирации", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_annualPET':                {'title': "ENVIREM: Годовая потенциальная эвапотранспирация", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_PETDriestQuarter':         {'title': "ENVIREM: Среднемесячная потенциальная эвапотранспирация самого сухого квартала", 'unit': '', 'scale': 1, 'diff': 0},
        'ENVIREM_PETColdestQuarter':        {'title': "ENVIREM: Среднемесячная потенциальная эвапотранспирация холодного квартала", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_ocs_0-30cm_mean_1000':          {'title': "SoilGrid: Запас органического углерода в почве на глубине 0-30 см, х10 кг/кв. м", 'unit': '', 'scale': 1, 'diff': 0},
    
        'SG_bdod_0-5cm_mean_1000':          {'title': "SoilGrid: Плотность грунта на глубине 0-5 см, х100 кг/л", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_bdod_5-15cm_mean_1000':         {'title': "SoilGrid: Плотность грунта на глубине 5-15 см, х100 кг/л", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_bdod_15-30cm_mean_1000':        {'title': "SoilGrid: Плотность грунта на глубине 15-30 см, х100 кг/л", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_bdod_30-60cm_mean_1000':        {'title': "SoilGrid: Плотность грунта на глубине 30-60 см, х100 кг/л", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_bdod_60-100cm_mean_1000':       {'title': "SoilGrid: Плотность грунта на глубине 60-100 см, х100 кг/л", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_bdod_100-200cm_mean_1000':      {'title': "SoilGrid: Плотность грунта на глубине 100-200 см, х100 кг/л", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_cec_0-5cm_mean_1000':           {'title': "SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 0-5 см, х10 смоль/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cec_5-15cm_mean_1000':          {'title': "SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 5-15 см, х10 смоль/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cec_15-30cm_mean_1000':         {'title': "SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 15-30 см, х10 смоль/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cec_30-60cm_mean_1000':         {'title': "SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 30-60 см, х10 смоль/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cec_60-100cm_mean_1000':        {'title': "SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 60-100 см, х10 смоль/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cec_100-200cm_mean_1000':       {'title': "SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 100-200 см, х10 смоль/кг", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_cfvo_0-5cm_mean_1000':          {'title': "SoilGrid: Объёмная доля крупных частиц на глубине 0-5 см, х100 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cfvo_5-15cm_mean_1000':         {'title': "SoilGrid: Объёмная доля крупных частиц на глубине 5-15 см, х100 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cfvo_15-30cm_mean_1000':        {'title': "SoilGrid: Объёмная доля крупных частиц на глубине 15-30 см, х100 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cfvo_30-60cm_mean_1000':        {'title': "SoilGrid: Объёмная доля крупных частиц на глубине 30-60 см, х100 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cfvo_60-100cm_mean_1000':       {'title': "SoilGrid: Объёмная доля крупных частиц на глубине 60-100 см, х100 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_cfvo_100-200cm_mean_1000':      {'title': "SoilGrid: Объёмная доля крупных частиц на глубине 100-200 см, х100 %", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_clay_0-5cm_mean_1000':          {'title': "SoilGrid: Содержание глины в почве на глубине 0-5 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_clay_5-15cm_mean_1000':         {'title': "SoilGrid: Содержание глины в почве на глубине 5-15 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_clay_15-30cm_mean_1000':        {'title': "SoilGrid: Содержание глины в почве на глубине 15-30 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_clay_30-60cm_mean_1000':        {'title': "SoilGrid: Содержание глины в почве на глубине 30-60 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_clay_60-100cm_mean_1000':       {'title': "SoilGrid: Содержание глины в почве на глубине 60-100 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_clay_100-200cm_mean_1000':      {'title': "SoilGrid: Содержание глины в почве на глубине 100-200 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_nitrogen_0-5cm_mean_1000':      {'title': "SoilGrid: Содержание азота в почве на глубине 0-5 см, х100 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_nitrogen_5-15cm_mean_1000':     {'title': "SoilGrid: Содержание азота в почве на глубине 5-15 см, х100 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_nitrogen_15-30cm_mean_1000':    {'title': "SoilGrid: Содержание азота в почве на глубине 15-30 см, х100 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_nitrogen_30-60cm_mean_1000':    {'title': "SoilGrid: Содержание азота в почве на глубине 30-60 см, х100 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_nitrogen_60-100cm_mean_1000':   {'title': "SoilGrid: Содержание азота в почве на глубине 60-100 см, х100 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_nitrogen_100-200cm_mean_1000':  {'title': "SoilGrid: Содержание азота в почве на глубине 100-200 см, х100 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_ocd_0-5cm_mean_1000':           {'title': "SoilGrid: Плотность органического углерода в почве на глубине 0-5 см, х10 кг/куб.м", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_ocd_5-15cm_mean_1000':          {'title': "SoilGrid: Плотность органического углерода в почве на глубине 5-15 см, х10 кг/куб.м", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_ocd_15-30cm_mean_1000':         {'title': "SoilGrid: Плотность органического углерода в почве на глубине 15-30 см, х10 кг/куб.м", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_ocd_30-60cm_mean_1000':         {'title': "SoilGrid: Плотность органического углерода в почве на глубине 30-60 см, х10 кг/куб.м", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_ocd_60-100cm_mean_1000':        {'title': "SoilGrid: Плотность органического углерода в почве на глубине 60-100 см, х10 кг/куб.м", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_ocd_100-200cm_mean_1000':       {'title': "SoilGrid: Плотность органического углерода в почве на глубине 100-200 см, х10 кг/куб.м", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_soc_0-5cm_mean_1000':           {'title': "SoilGrid: Почвенный органический углерод на глубине 0-5 см, х10 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_soc_5-15cm_mean_1000':          {'title': "SoilGrid: Почвенный органический углерод на глубине 5-15 см, х10 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_soc_15-30cm_mean_1000':         {'title': "SoilGrid: Почвенный органический углерод на глубине 15-30 см, х10 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_soc_30-60cm_mean_1000':         {'title': "SoilGrid: Почвенный органический углерод на глубине 30-60 см, х10 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_soc_60-100cm_mean_1000':        {'title': "SoilGrid: Почвенный органический углерод на глубине 60-100 см, х10 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_soc_100-200cm_mean_1000':       {'title': "SoilGrid: Почвенный органический углерод на глубине 100-200 см, х10 г/кг", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_phh2o_0-5cm_mean_1000':         {'title': "SoilGrid: pH воды на глубине 0-5 см, х10", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_phh2o_5-15cm_mean_1000':        {'title': "SoilGrid: pH воды на глубине 5-15 см, х10", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_phh2o_15-30cm_mean_1000':       {'title': "SoilGrid: pH воды на глубине 15-30 см, х10", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_phh2o_30-60cm_mean_1000':       {'title': "SoilGrid: pH воды на глубине 30-60 см, х10", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_phh2o_60-100cm_mean_1000':      {'title': "SoilGrid: pH воды на глубине 60-100 см, х10", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_phh2o_100-200cm_mean_1000':     {'title': "SoilGrid: pH воды на глубине 100-200 см, х10", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_sand_0-5cm_mean_1000':          {'title': "SoilGrid: Содержание песка в почве на глубине 0-5 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_sand_5-15cm_mean_1000':         {'title': "SoilGrid: Содержание песка в почве на глубине 5-15 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_sand_15-30cm_mean_1000':        {'title': "SoilGrid: Содержание песка в почве на глубине 15-30 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_sand_30-60cm_mean_1000':        {'title': "SoilGrid: Содержание песка в почве на глубине 30-60 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_sand_60-100cm_mean_1000':       {'title': "SoilGrid: Содержание песка в почве на глубине 60-100 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_sand_100-200cm_mean_1000':      {'title': "SoilGrid: Содержание песка в почве на глубине 100-200 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_silt_0-5cm_mean_1000':          {'title': "SoilGrid: Содержание илистых пород в почве на глубине 0-5 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_silt_5-15cm_mean_1000':         {'title': "SoilGrid: Содержание илистых пород в почве на глубине 5-15 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_silt_15-30cm_mean_1000':        {'title': "SoilGrid: Содержание илистых пород в почве на глубине 15-30 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_silt_30-60cm_mean_1000':        {'title': "SoilGrid: Содержание илистых пород в почве на глубине 30-60 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_silt_60-100cm_mean_1000':       {'title': "SoilGrid: Содержание илистых пород в почве на глубине 60-100 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_silt_100-200cm_mean_1000':      {'title': "SoilGrid: Содержание илистых пород в почве на глубине 100-200 см, х10 г/100 г", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_wv0010_0-5cm_mean_1000':        {'title': "SoilGrid: Объемная влажность при 10 кПа на глубине 0-5 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0010_5-15cm_mean_1000':       {'title': "SoilGrid: Объемная влажность при 10 кПа на глубине 5-15 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0010_15-30cm_mean_1000':      {'title': "SoilGrid: Объемная влажность при 10 кПа на глубине 15-30 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0010_30-60cm_mean_1000':      {'title': "SoilGrid: Объемная влажность при 10 кПа на глубине 30-60 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0010_60-100cm_mean_1000':     {'title': "SoilGrid: Объемная влажность при 10 кПа на глубине 60-100 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0010_100-200cm_mean_1000':    {'title': "SoilGrid: Объемная влажность при 10 кПа на глубине 100-200 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
    
        'SG_wv0033_0-5cm_mean_1000':        {'title': "SoilGrid: Объемная влажность при 33 кПа на глубине 0-5 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0033_5-15cm_mean_1000':       {'title': "SoilGrid: Объемная влажность при 33 кПа на глубине 5-15 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0033_15-30cm_mean_1000':      {'title': "SoilGrid: Объемная влажность при 33 кПа на глубине 15-30 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0033_30-60cm_mean_1000':      {'title': "SoilGrid: Объемная влажность при 33 кПа на глубине 30-60 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0033_60-100cm_mean_1000':     {'title': "SoilGrid: Объемная влажность при 33 кПа на глубине 60-100 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv0033_100-200cm_mean_1000':    {'title': "SoilGrid: Объемная влажность при 33 кПа на глубине 100-200 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        
        'SG_wv1500_0-5cm_mean_1000':        {'title': "SoilGrid: Объемная влажность при 1500 кПа на глубине 0-5 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv1500_5-15cm_mean_1000':       {'title': "SoilGrid: Объемная влажность при 1500 кПа на глубине 5-15 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv1500_15-30cm_mean_1000':      {'title': "SoilGrid: Объемная влажность при 1500 кПа на глубине 15-30 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv1500_30-60cm_mean_1000':      {'title': "SoilGrid: Объемная влажность при 1500 кПа на глубине 30-60 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv1500_60-100cm_mean_1000':     {'title': "SoilGrid: Объемная влажность при 1500 кПа на глубине 60-100 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
        'SG_wv1500_100-200cm_mean_1000':    {'title': "SoilGrid: Объемная влажность при 1500 кПа на глубине 100-200 см, х10 %", 'unit': '', 'scale': 1, 'diff': 0},
    }
    
    return bio_info