def get_predictors_info():
    bio_info = {
        'roughness_std3x3':                 {'title': 'Пересечённость рельефа (стандартное отклонение на сетке 3х3 км)', 'unit': 'м/м', 'scale': 1, 'diff': 0, 'min_val': 0},
        'slope_deg':                        {'title': 'Уклон рельефа на заданном шаге модели', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'distance_to_cities':               {'title': 'Расстояние до городской застройки', 'unit': 'км', 'scale': 1, 'diff': 0, 'step': 1, 'min_val': 0, 'min_val': 0},
        'distance_to_water':                {'title': 'Расстояние до водоёмов', 'unit': 'км', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},

        'human_bias_alls':                  {'title': 'Human bias factor: все классы', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'human_bias_Insecta':               {'title': 'Human bias factor: насекомые', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'human_bias_Mammalia':              {'title': 'Human bias factor: млекопитающие', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'human_bias_Aves':                  {'title': 'Human bias factor: птицы', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'human_bias_Amphibia':              {'title': 'Human bias factor: амфибии', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'human_bias_Squamata':              {'title': 'Human bias factor: чешуйчатые', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'human_bias_Testudines':            {'title': 'Human bias factor: черепахи', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},

        'wc2.1_30s_elev':                   {'title': 'WC ELEV: Высота над уровнем моря', 'unit': 'м', 'scale': 1, 'diff': 0, 'step': 1, 'min_val': -200},
        
        'wc2.1_30s_bio_1':                  {'title': 'WC BIO1: Среднегодовая температура (Mean annual temperature)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'wc2.1_30s_bio_2':                  {'title': 'WC BIO2: Среднегодовая суточная температурная амплитуда (Mean diurnal range)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': 0},
        'wc2.1_30s_bio_3':                  {'title': 'WC BIO3: Изотермичность/сезонность температуры (Temperature seasonality, BIO2 / BIO7)', 'unit': '', 'scale': 100, 'diff': 0, 'min_val': 0},
        'wc2.1_30s_bio_4':                  {'title': 'WC BIO4: Сезонность температуры (Temperature seasonality, стандартное отклонение)', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0}, 
        'wc2.1_30s_bio_5':                  {'title': 'WC BIO5: Средняя максимальная температура самого теплого месяца (Max temperature of warmest month)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'wc2.1_30s_bio_6':                  {'title': 'WC BIO6: Средняя минимальная температура самого холодного месяца (Min temperature of coldest month)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'wc2.1_30s_bio_7':                  {'title': 'WC BIO7: Годовая температурная амплитуда (Annual temperature range, BIO5 - BIO6)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': 0},
        'wc2.1_30s_bio_8':                  {'title': 'WC BIO8: Средняя температура самого влажного квартала (Mean temperature of wettest quarter)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'wc2.1_30s_bio_9':                  {'title': 'WC BIO9: Средняя температура самого сухого квартала (Mean temperature of driest quarter)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'wc2.1_30s_bio_10':                 {'title': 'WC BIO10: Средняя температура самого теплого квартала (Mean temperature of warmest quarter)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'wc2.1_30s_bio_11':                 {'title': 'WC BIO11: Средняя температура самого холодного квартала (Mean temperature of coldest quarter)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'wc2.1_30s_bio_12':                 {'title': 'WC BIO12: Годовое количество осадков (Annual precipitation)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'wc2.1_30s_bio_13':                 {'title': 'WC BIO13: Количество осадков самого влажного месяца (Precipitation of wettest month)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'wc2.1_30s_bio_14':                 {'title': 'WC BIO14: Количество осадков самого сухого месяца (Precipitation of driest month)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'wc2.1_30s_bio_15':                 {'title': 'WC BIO15: Сезонность осадков (Precipitation seasonality)', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'wc2.1_30s_bio_16':                 {'title': 'WC BIO16: Количество осадков самого влажного квартала (Precipitation of wettest quarter)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'wc2.1_30s_bio_17':                 {'title': 'WC BIO17: Количество осадков самого сухого квартала (Precipitation of driest quarter)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'wc2.1_30s_bio_18':                 {'title': 'WC BIO18: Количество осадков самого теплого квартала (Precipitation of warmest quarter)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'wc2.1_30s_bio_19':                 {'title': 'WC BIO19: Количество осадков самого холодного квартала (Precipitation of coldest quarter)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'CHELSA_bio01_1981-2010_V.2.1':     {'title': 'CHELSA BIO1: Среднегодовая температура (Mean annual temperature)', 'unit': '°C', 'scale': 10, 'diff': 2732},
        'CHELSA_bio02_1981-2010_V.2.1':     {'title': 'CHELSA BIO2: Среднегодовая суточная температурная амплитуда (Mean diurnal range)', 'unit': '°C', 'scale': 10, 'diff': 0, 'min_val': 0},
        'CHELSA_bio03_1981-2010_V.2.1':     {'title': 'CHELSA BIO3: Изотермичность/сезонность температуры (Temperature seasonality, BIO2 / BIO7)', 'unit': '', 'scale': 1000, 'diff': 0, 'min_val': 0},
        'CHELSA_bio04_1981-2010_V.2.1':     {'title': 'CHELSA BIO4: Сезонность температуры (Temperature seasonality, стандартное отклонение)', 'unit': '', 'scale': 1000, 'diff': 0, 'min_val': 0}, 
        'CHELSA_bio05_1981-2010_V.2.1':     {'title': 'CHELSA BIO5: Средняя максимальная температура самого теплого месяца (Max temperature of warmest month)', 'unit': '°C', 'scale': 10, 'diff': 2732},
        'CHELSA_bio06_1981-2010_V.2.1':     {'title': 'CHELSA BIO6: Средняя минимальная температура самого холодного месяца (Min temperature of coldest month)', 'unit': '°C', 'scale': 10, 'diff': 2732},
        'CHELSA_bio07_1981-2010_V.2.1':     {'title': 'CHELSA BIO7: Годовая температурная амплитуда (Annual temperature range, BIO5 - BIO6)', 'unit': '°C', 'scale': 10, 'diff': 0},
        'CHELSA_bio08_1981-2010_V.2.1':     {'title': 'CHELSA BIO8: Средняя температура самого влажного квартала (Mean temperature of wettest quarter)', 'unit': '°C', 'scale': 10, 'diff': 2732},
        'CHELSA_bio09_1981-2010_V.2.1':     {'title': 'CHELSA BIO9: Средняя температура самого сухого квартала (Mean temperature of driest quarter)', 'unit': '°C', 'scale': 10, 'diff': 2732},
        'CHELSA_bio10_1981-2010_V.2.1':     {'title': 'CHELSA BIO10: Средняя температура самого теплого квартала (Mean temperature of warmest quarter)', 'unit': '°C', 'scale': 10, 'diff': 2732},
        'CHELSA_bio11_1981-2010_V.2.1':     {'title': 'CHELSA BIO11: Средняя температура самого холодного квартала (Mean temperature of coldest quarter)', 'unit': '°C', 'scale': 10, 'diff': 2732},
        'CHELSA_bio12_1981-2010_V.2.1':     {'title': 'CHELSA BIO12: Годовое количество осадков (Annual precipitation)', 'unit': 'мм', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_bio13_1981-2010_V.2.1':     {'title': 'CHELSA BIO13: Количество осадков самого влажного месяца (Precipitation of wettest month)', 'unit': 'мм', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_bio14_1981-2010_V.2.1':     {'title': 'CHELSA BIO14: Количество осадков самого сухого месяца (Precipitation of driest month)', 'unit': 'мм', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_bio15_1981-2010_V.2.1':     {'title': 'CHELSA BIO15: Сезонность осадков (Precipitation seasonality)', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0},
        'CHELSA_bio16_1981-2010_V.2.1':     {'title': 'CHELSA BIO16: Количество осадков самого влажного квартала (Precipitation of wettest quarter)', 'unit': 'мм', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_bio17_1981-2010_V.2.1':     {'title': 'CHELSA BIO17: Количество осадков самого сухого квартала (Precipitation of driest quarter)', 'unit': 'мм', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_bio18_1981-2010_V.2.1':     {'title': 'CHELSA BIO18: Количество осадков самого теплого квартала (Precipitation of warmest quarter)', 'unit': 'мм', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_bio19_1981-2010_V.2.1':     {'title': 'CHELSA BIO19: Количество осадков самого холодного квартала (Precipitation of coldest quarter)', 'unit': 'мм', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'CHELSA_cmimean_1981-2010_V.2.1':   {'title': 'CHELSA CMI MEAN: Средний месячный индекс влажности климата за 1 год', 'unit': 'кг/(кв.м.*мес)', 'scale': 10, 'diff': 0},
        'CHELSA_cmimin_1981-2010_V.2.1':    {'title': 'CHELSA CMI MIN: Индекс влажности климата месяца с наибольшим дефицитом осадков', 'unit': 'кг/(кв.м.*мес)', 'scale': 10, 'diff': 0},
        'CHELSA_cmimax_1981-2010_V.2.1':    {'title': 'CHELSA CMI MAX: Индекс влажности климата месяца с наибольшим избытком осадков', 'unit': 'кг/(кв.м.*мес)', 'scale': 10, 'diff': 0},
        'CHELSA_cmirange_1981-2010_V.2.1':  {'title': 'CHELSA CMI RANGE: Разница CHELSA CMI MAX-CHELSA CMI MIN', 'unit': 'кг/(кв.м.*мес)', 'scale': 10, 'diff': 0},
        
        'CHELSA_cltmean_1981-2010_V.2.1':   {'title': 'CHELSA CLT MEAN: Средний процент общей облачности', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'CHELSA_cltmin_1981-2010_V.2.1':    {'title': 'CHELSA CLT MIN: Процент общей облачности наименее облачного месяца', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'CHELSA_cltmax_1981-2010_V.2.1':    {'title': 'CHELSA CLT MAX: Процент общей облачности наиболее облачного месяца', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'CHELSA_cltrange_1981-2010_V.2.1':  {'title': 'CHELSA CLT RANGE: Разница CHELSA CLT MAX - CHELSA CLT MIN', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        
        'CHELSA_hursmean_1981-2010_V.2.1':  {'title': 'CHELSA HURS MEAN: Средняя относительная влажность у поверхности', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'CHELSA_hursmin_1981-2010_V.2.1':   {'title': 'CHELSA HURS MIN: Средняя относительная влажность у поверхности наименее влажного месяца', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'CHELSA_hursmax_1981-2010_V.2.1':   {'title': 'CHELSA HURS MAX: Средняя относительная влажность у поверхности наиболее влажного месяца', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'CHELSA_hursrange_1981-2010_V.2.1': {'title': 'CHELSA HURS RANGE: Разница CHELSA HURS MAX и CHELSA HURS MIN', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        
        'CHELSA_fcf_1981-2010_V.2.1':       {'title': 'CHELSA FCF: Количество переходов через ноль (замерзание-оттаивание) в год', 'unit': 'раз', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_fgd_1981-2010_V.2.1':       {'title': 'CHELSA FGD: Юлианский день, отмечающий первое наступление условий для вегетационного периода', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_gdd0_1981-2010_V.2.1':      {'title': 'CHELSA GDD0: Сумма среднесуточных температур выше 0 °C, накопленная за год', 'unit': '°C', 'scale': 10, 'diff': 0, 'min_val': 0, 'max_val': 100000},
        'CHELSA_gdd5_1981-2010_V.2.1':      {'title': 'CHELSA GDD5: Сумма среднесуточных температур выше 5 °C, накопленная за год', 'unit': '°C', 'scale': 10, 'diff': 0, 'min_val': 0, 'max_val': 100000},
        'CHELSA_gdd10_1981-2010_V.2.1':     {'title': 'CHELSA GDD10: Сумма среднесуточных температур выше 10 °C, накопленная за год', 'unit': '°C', 'scale': 10, 'diff': 0, 'min_val': 0, 'max_val': 10000},
        'CHELSA_gdgfgd5_1981-2010_V.2.1':   {'title': 'CHELSA GDG FGD5: Юлианский день первого наступления среднесуточной температуры выше 5 °C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_gdgfgd10_1981-2010_V.2.1':  {'title': 'CHELSA GDG FGD10: Юлианский день первого наступления среднесуточной температуры выше 10 °C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_gddlgd0_1981-2010_V.2.1':   {'title': 'CHELSA GDG LGD10: Юлианский день последнего наступления среднесуточной температуры выше 10 °C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_gddlgd10_1981-2010_V.2.1':  {'title': 'CHELSA GDG LGD5: Юлианский день последнего наступления среднесуточной температуры выше 5 °C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_gddlgd5_1981-2010_V.2.1':   {'title': 'CHELSA GDG LGD0: Юлианский день последнего наступления среднесуточной температуры выше 0 °C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_gsl_1981-2010_V.2.1':       {'title': 'CHELSA GSL: Количество дней между первым и последним наступлением условий для вегетационного периода', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'CHELSA_gsp_1981-2010_V.2.1':       {'title': 'CHELSA GSP: Общее количество осадков, накопленное за период вегетационного сезона', 'unit': 'кг/кв.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'max_val': 1000},
        'CHELSA_gst_1981-2010_V.2.1':       {'title': 'CHELSA GST: Среднесуточная средняя температура за все дни вегетационного периода', 'unit': '°C', 'scale': 10, 'diff': 2732, 'max_val': 100},
        
        'CHELSA_petmean_1981-2010_V.2.1':   {'title': 'CHELSA PET MEAN: Минимальная месячная потенциальная эвапотранспирация', 'unit': '', 'scale': 100, 'diff': 0},
        'CHELSA_petmin_1981-2010_V.2.1':    {'title': 'CHELSA PET MIN: Средняя месячная потенциальная эвапотранспирация', 'unit': '', 'scale': 100, 'diff': 0},
        'CHELSA_petmax_1981-2010_V.2.1':    {'title': 'CHELSA PET MAX: Максимальная месячная потенциальная эвапотранспирация', 'unit': '', 'scale': 100, 'diff': 0},
        'CHELSA_petrange_1981-2010_V.2.1':  {'title': 'CHELSA PET RANGE: Годовой диапазон месячной потенциальной эвапотранспирации', 'unit': '', 'scale': 100, 'diff': 0},
        
        'CHELSA_rsdsmean_1981-2010_V.2.1':  {'title': 'CHELSA RSDS MEAN: Минимальный месячный поток коротковолновой радиации', 'unit': '', 'scale': 1000, 'diff': 0, 'min_val': 0},
        'CHELSA_rsdsmin_1981-2010_V.2.1':   {'title': 'CHELSA RSDS MIN: Средний месячный поток коротковолновой радиации', 'unit': '', 'scale': 1000, 'diff': 0, 'min_val': 0},
        'CHELSA_rsdsmax_1981-2010_V.2.1':   {'title': 'CHELSA RSDS MAX: Максимальный месячный поток коротковолновой радиации', 'unit': '', 'scale': 1000, 'diff': 0, 'min_val': 0},
        'CHELSA_rsdsrange_1981-2010_V.2.1': {'title': 'CHELSA RSDS RANGE: Годовой диапазон месячного потока коротковолновой радиации', 'unit': '', 'scale': 1000, 'diff': 0, 'min_val': 0},
        
        'CHELSA_vpdmean_1981-2010_V.2.1':   {'title': 'CHELSA VPD MEAN: Средний месячный дефицит давления водяного пара', 'unit': 'Па', 'scale': 10, 'diff': 0},
        'CHELSA_vpdmin_1981-2010_V.2.1':    {'title': 'CHELSA VPD MIN: Минимальный месячный дефицит давления водяного пара', 'unit': 'Па', 'scale': 10, 'diff': 0},
        'CHELSA_vpdmax_1981-2010_V.2.1':    {'title': 'CHELSA VPD MAX: Максимальный месячный дефицит давления водяного пара', 'unit': 'Па', 'scale': 10, 'diff': 0},
        'CHELSA_vpdrange_1981-2010_V.2.1':  {'title': 'CHELSA VPD RANGE: Годовой диапазон месячного дефицита давления водяного пара', 'unit': 'Па', 'scale': 0.1, 'diff': 0},
        
        'CHELSA_sfcWindmean_1981-2010_V.2.1':{'title': 'CHELSA SFCW MEAN: Минимальная месячная скорость ветра у поверхности', 'unit': 'м/с', 'scale': 1000, 'diff': 0, 'min_val': 0},
        'CHELSA_sfcWindmin_1981-2010_V.2.1': {'title': 'CHELSA SFCW MIN: Средняя месячная скорость ветра у поверхности', 'unit': 'м/с', 'scale': 1000, 'diff': 0, 'min_val': 0},
        'CHELSA_sfcWindmax_1981-2010_V.2.1': {'title': 'CHELSA SFCW MAX: Максимальная месячная скорость ветра у поверхности', 'unit': 'м/с', 'scale': 1000, 'diff': 0, 'min_val': 0},
        'CHELSA_sfcWindrange_1981-2010_V.2.1':{'title': 'CHELSA SFCW RANGE: Годовой диапазон месячной скорости ветра у поверхности', 'unit': 'м/с', 'scale': 1000, 'diff': 0, 'min_val': 0},
        
        'CHELSA_lgd_1981-2010_V.2.1':       {'title': 'CHELSA LGD: Последний день вегетационного периода', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1, 'max_val': 365},
        'CHELSA_ngd0_1981-2010_V.2.1':      {'title': 'CHELSA NGD0: Количество дней вегетации с температурой > 0°C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1, 'max_val': 365},
        'CHELSA_ngd5_1981-2010_V.2.1':      {'title': 'CHELSA NGD5: Количество дней вегетации с температурой > 5°C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1, 'max_val': 365},
        'CHELSA_ngd10_1981-2010_V.2.1':     {'title': 'CHELSA NGD10: Количество дней вегетации с температурой > 10°C', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1, 'max_val': 365},
        'CHELSA_npp_1981-2010_V.2.1':       {'title': 'CHELSA NPP: Чистая первичная продуктивность (UNESCO, VIII, 2:5-10)', 'unit': '', 'scale': 10, 'diff': 0},
        'CHELSA_scd_1981-2010_V.2.1':       {'title': 'CHELSA SCD: Количество дней снежного покрова', 'unit': 'дн', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1, 'max_val': 365},
        'CHELSA_swb_1981-2010_V.2.1':       {'title': 'CHELSA SWB: Водный баланс участка', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': -2000},
        'CHELSA_swe_1981-2010_V.2.1':       {'title': 'CHELSA SWE: Эквивалент водяного содержания снега', 'unit': 'кг/(кв.м.*год)', 'scale': 10, 'diff': 0, 'max_val': 1000},
        
        'CHELSA_kg2_1981-2010_V.2.1_1':        {'title': 'CHELSA KG2 климат по Кёппену: Af - тропический влажный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_2':        {'title': 'CHELSA KG2 климат по Кёппену: Am - тропический мусонный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_3':        {'title': 'CHELSA KG2 климат по Кёппену: As - тропический саванн с сухим летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_4':        {'title': 'CHELSA KG2 климат по Кёппену: Aw - тропический саванн с сухой зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_5':        {'title': 'CHELSA KG2 климат по Кёппену: BWk - сухой пустынный холодный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_6':        {'title': 'CHELSA KG2 климат по Кёппену: BWh - сухой пустынный жаркий', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_7':        {'title': 'CHELSA KG2 климат по Кёппену: Bsk - сухой степной холодный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_8':        {'title': 'CHELSA KG2 климат по Кёппену: BSh - сухой степной жаркий', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_9':        {'title': 'CHELSA KG2 климат по Кёппену: Cfa - умеренный без сухого сезона с жарким летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_10':       {'title': 'CHELSA KG2 климат по Кёппену: CFb - умеренный без сухого сезона с тёплым летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_11':       {'title': 'CHELSA KG2 климат по Кёппену: Cfc - умеренный без сухого сезона с холодным летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_12':       {'title': 'CHELSA KG2 климат по Кёппену: Csa - умеренный с сухим жарким летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_13':       {'title': 'CHELSA KG2 климат по Кёппену: Csb - умеренный с сухим тёплым летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_14':       {'title': 'CHELSA KG2 климат по Кёппену: Csc - умеренный с сухим холодным летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_15':       {'title': 'CHELSA KG2 климат по Кёппену: Cwa - умеренный с сухой зимой и жарким летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_16':       {'title': 'CHELSA KG2 климат по Кёппену: Cwb - умеренный с сухой зимой и тёплым летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_17':       {'title': 'CHELSA KG2 климат по Кёппену: Cwc - умеренный с сухой зимой и холодным летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_18':       {'title': 'CHELSA KG2 климат по Кёппену: Dfa - континентальный без сухого сезона с жарким летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_19':       {'title': 'CHELSA KG2 климат по Кёппену: Dfb - континентальный без сухого сезона с тёплым летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_20':       {'title': 'CHELSA KG2 климат по Кёппену: Dfc - континентальный без сухого сезона с холодным летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_21':       {'title': 'CHELSA KG2 климат по Кёппену: Dfd - континентальный без сухого сезона с очень холодной зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_22':       {'title': 'CHELSA KG2 климат по Кёппену: Dsa - континентальный с сухим и жарким летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_23':       {'title': 'CHELSA KG2 климат по Кёппену: Dsb - континентальный с сухим и тёплым летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_24':       {'title': 'CHELSA KG2 климат по Кёппену: Dsc - континентальный с сухим и холодным летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_25':       {'title': 'CHELSA KG2 климат по Кёппену: Dsd - континентальный с сухим летом и очень холодной зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_26':       {'title': 'CHELSA KG2 климат по Кёппену: Dwa - континентальный с сухой зимой и жарким летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_27':       {'title': 'CHELSA KG2 климат по Кёппену: Dwb - континентальный с сухой зимой и тёплым летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_28':       {'title': 'CHELSA KG2 климат по Кёппену: Dwc - континентальный с сухой зимой и холодным летом', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_29':       {'title': 'CHELSA KG2 климат по Кёппену: Dwd - континентальный с сухой и очень холодной зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_30':       {'title': 'CHELSA KG2 климат по Кёппену: ET - тундра', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg2_1981-2010_V.2.1_31':       {'title': 'CHELSA KG2 климат по Кёппену: EF - вечная мерзлота', 'unit': 'да', 'scale': 1, 'diff': 0},
        
        'CHELSA_kg3_1981-2010_V.2.1_1':        {'title': 'CHELSA KG3 климат по Виссманну: I_A - экваториальные дождливые леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_2':        {'title': 'CHELSA KG3 климат по Виссманну: I_F - дождливые леса с сухим сезоном', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_3':        {'title': 'CHELSA KG3 климат по Виссманну: I_T - саванны', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_4':        {'title': 'CHELSA KG3 климат по Виссманну: I_S - тропические степи', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_5':        {'title': 'CHELSA KG3 климат по Виссманну: I_D - тропические пустыни', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_6':        {'title': 'CHELSA KG3 климат по Виссманну: II_Fa', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_7':        {'title': 'CHELSA KG3 климат по Виссманну: II_Fb', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_8':        {'title': 'CHELSA KG3 климат по Виссманну: II_Tw', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_9':        {'title': 'CHELSA KG3 климат по Виссманну: II_Ts', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_10':       {'title': 'CHELSA KG3 климат по Виссманну: II_S', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_11':       {'title': 'CHELSA KG3 климат по Виссманну: II_D', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_12':       {'title': 'CHELSA KG3 климат по Виссманну: III_F', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_13':       {'title': 'CHELSA KG3 климат по Виссманну: III_Tw - смешанные леса с сухой зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_14':       {'title': 'CHELSA KG3 климат по Виссманну: III_Ts - смешанные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_15':       {'title': 'CHELSA KG3 климат по Виссманну: III_S', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_16':       {'title': 'CHELSA KG3 климат по Виссманну: III_D', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_17':       {'title': 'CHELSA KG3 климат по Виссманну: IV_F - увлажнённые северные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_18':       {'title': 'CHELSA KG3 климат по Виссманну: IV_T - северные леса с сухой зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_19':       {'title': 'CHELSA KG3 климат по Виссманну: IV_S - северные степи', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_20':       {'title': 'CHELSA KG3 климат по Виссманну: IV_D - северные пустыни', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_21':       {'title': 'CHELSA KG3 климат по Виссманну: V - тундра', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg3_1981-2010_V.2.1_22':       {'title': 'CHELSA KG3 климат по Виссманну: VI - вечная мерзлота', 'unit': 'да', 'scale': 1, 'diff': 0},
        
        'CHELSA_kg4_1981-2010_V.2.1_1':        {'title': 'CHELSA KG4 климат по Торнтвейту: тропический с сезоном дождей', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_2':        {'title': 'CHELSA KG4 климат по Торнтвейту: тропический с равномерным увлажнением', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_3':        {'title': 'CHELSA KG4 климат по Торнтвейту: тропический полуувлажнённый', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_4':        {'title': 'CHELSA KG4 климат по Торнтвейту: тропический полупустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_5':        {'title': 'CHELSA KG4 климат по Торнтвейту: тропический пустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_6':        {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно тёплый с сезоном дождей', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_7':        {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно тёплый с равномерным увлажнением', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_8':        {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно тёплый полуувлажнённый', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_9':        {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно тёплый полупустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_10':       {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно тёплый пустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_11':       {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно холодный с сезоном дождей', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_12':       {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно холодный с равномерным увлажнением', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_13':       {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно холодный полуувлажнённый', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_14':       {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно холодный полупустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_15':       {'title': 'CHELSA KG4 климат по Торнтвейту: умеренно холодный пустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_16':       {'title': 'CHELSA KG4 климат по Торнтвейту: таёжный с сезоном дождей', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_17':       {'title': 'CHELSA KG4 климат по Торнтвейту: таёжный с равномерным увлажнением', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_18':       {'title': 'CHELSA KG4 климат по Торнтвейту: таёжный полуувлажнённый', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_19':       {'title': 'CHELSA KG4 климат по Торнтвейту: таёжный полупустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_20':       {'title': 'CHELSA KG4 климат по Торнтвейту: таёжный пустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_21':       {'title': 'CHELSA KG4 климат по Торнтвейту: тундровый с сезоном дождей', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_22':       {'title': 'CHELSA KG4 климат по Торнтвейту: тундровый с равномерным увлажнением', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_23':       {'title': 'CHELSA KG4 климат по Торнтвейту: тундровый полуувлажнённый', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_24':       {'title': 'CHELSA KG4 климат по Торнтвейту: тундровый полупустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_25':       {'title': 'CHELSA KG4 климат по Торнтвейту: тундровый пустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_26':       {'title': 'CHELSA KG4 климат по Торнтвейту: полярный с сезоном дождей', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_27':       {'title': 'CHELSA KG4 климат по Торнтвейту: полярный с равномерным увлажнением', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_28':       {'title': 'CHELSA KG4 климат по Торнтвейту: полярный полуувлажнённый', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_29':       {'title': 'CHELSA KG4 климат по Торнтвейту: полярный полупустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg4_1981-2010_V.2.1_30':       {'title': 'CHELSA KG4 климат по Торнтвейту: полярный пустынный', 'unit': 'да', 'scale': 1, 'diff': 0},
        
        'CHELSA_kg5_1981-2010_V.2.1_1':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: I_1 - полярные ледяные пустыни', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_2':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: I_2 - полярный осыпной пояс', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_3':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: I_3 - тундра', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_4':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: I_4 - субполярный туссоковые луга и болота', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_5':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: II_1 - прибрежные влажные хвойные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_6':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: II-2 - континентальные хвойные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_7':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: II_3 - высококонтинентальные сухие хвойные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_8':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_1 - вечнозеленые широколиственные и смешанные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_9':        {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_2 - прибрежные широколиственные и смешанные листопадные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_10':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_3 - субприбрежные широколиственные и смешанные листопадные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_11':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_4 - субконтинентальные широколиственные и смешанные листопадные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_12':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_5 - континентальные широколиственные и смешанные листопадные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_13':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_6 - высококонтинентальные широколиственные и смешанные листопадные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_14':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_7 -  широколиственные и смешанные листопадные леса и лесостепь, предпочитающая тепло, но выдерживающая холод и засуху зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_15':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_7a - термофильные сухие леса и лесостепь, выдерживающие умеренно суровые зимы', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_16':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_8 - влажные широколиственные и смешанные листопадные леса, предпочитающие тепло', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_17':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_9 - высокие травянистые степи с многолетними травами', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_18':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_9a - влажные степи с мягкими зимами', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_19':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_10 - короткотравные или кустарниковые равнины', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_20':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_10a - степь с короткой травой, кустарниками и колючками', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_21':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_11 - центрально- и восточноазиатская степь с травой и кустарниками', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_22':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_12 - полупустыни и пустыни с холодными зимами', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_23':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: III_12a - полупустыни и пустыни с мягкими зимами', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_24':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: IV_1 - субтропические жестколистные и хвойные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_25':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: IV_2 - субтропические травянистые и кустарниковые степи', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_26':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: IV_3 - субтропические колючие и суккулентные степи', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_27':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: IV_4 - субтропические степи с короткой травой, жестколиственными монсунными лесами и лесостепью', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_28':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: IV_5 - субтропические полупустыни и пустыни', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_29':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: IV_6 - субтропические высокогорные луга', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_30':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: IV_7 - субтропические влажные леса (лавр и хвойные леса)', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_31':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: V_1 - вечнозеленые тропические влажные леса и переходные полулистопадные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_32':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: V_2 - влажные тропические леса с сезонным листопадом и влажные саванны', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_33':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: V_2a - переходные полулистопадные леса', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_34':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: V_3 - сухие тропические леса с сезонным листопадом и сухие саванны', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_35':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: V_4 - тропические колючие, суккулентные леса и саванны', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_36':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: V_4a - тропический сухой климат с влажными месяцами зимой', 'unit': 'да', 'scale': 1, 'diff': 0},
        'CHELSA_kg5_1981-2010_V.2.1_37':       {'title': 'CHELSA KG5 климат по Троллю-Пфаффену: V_5 - тропические полупустыни и пустыни', 'unit': 'да', 'scale': 1, 'diff': 0},
        
        
        'Consensus_reduced_class_1':        {'title': 'EE CLC1: Вечнозелёные/Листопадные хвойные деревья (Evergreen/Deciduous Needleleaf Trees)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_2':        {'title': 'EE CLC2: Вечнозелёные широколистные деревья (Evergreen Broadleaf Trees)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_3':        {'title': 'EE CLC3: Листопадные широколистные деревья (Deciduous Broadleaf Trees)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_4':        {'title': 'EE CLC4: Смешанные/Другие деревья (Mixed/Other Trees)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_5':        {'title': 'EE CLC5: Кустарники (Shrubs)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_6':        {'title': 'EE CLC6: Травянистая растительность (Herbaceous Vegetation)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_7':        {'title': 'EE CLC7: Культивируемая и управляемая растительность (Cultivated and Managed Vegetation)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_8':        {'title': 'EE CLC8: Регулярно затопляемая растительность (Regularly Flooded Vegetation)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_9':        {'title': 'EE CLC9: Городская/Застроенная территория (Urban/Built-up)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_10':       {'title': 'EE CLC10: Снег/Лёд (Snow/Ice)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_11':       {'title': 'EE CLC11: Голые земли / Бесплодные земли (Barren)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
        'Consensus_reduced_class_12':       {'title': 'EE CLC12: Открытые водные пространства (Open Water)', 'unit': '%', 'scale': 1, 'diff': 0, 'min_val': 0, 'max_val': 100, 'step': 1},
    
        'ENVIREM_thermicityIndex':          {'title': 'ENVIREM: Компенсированный индекс термичности', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_monthCountByTemp10':       {'title': 'ENVIREM: Количество месяцев со средней температурой выше 10 гр.', 'unit': 'мес', 'scale': 1, 'diff': 0, 'min_val': 0, 'step': 1},
        'ENVIREM_minTempWarmest':           {'title': 'ENVIREM: Минимальная температура самого теплого месяца', 'unit': '°C', 'scale': 10, 'diff': 0, 'min_val': -10},
        'ENVIREM_maxTempColdest':           {'title': 'ENVIREM: Максимальная температура самого холодного месяца', 'unit': '°C', 'scale': 10, 'diff': 0, 'min_val': -30},
        'ENVIREM_growingDegDays5':          {'title': 'ENVIREM: Сумма средних месячных температур для месяцев со средней температурой выше 5°, умноженная на количество дней', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_growingDegDays0':          {'title': 'ENVIREM: Сумма средних месячных температур для месяцев со средней температурой выше 0°, умноженная на количество дней', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_embergerQ':                {'title': 'ENVIREM: Эмбержеровский плювиотермический коэффициент', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_continentality':           {'title': 'ENVIREM: Континентальность (средняя температура самого теплого месяца минус средняя температура самого холодного месяца)', 'unit': '°C', 'scale': 1, 'diff': 0, 'min_val': -100},
        'ENVIREM_climaticMoistureIndex':    {'title': 'ENVIREM: Климатический индекс влажности (показатель относительной влажности и сухости)', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': -100},
        'ENVIREM_aridityIndexThornthwaite': {'title': 'ENVIREM: Индекс аридности Торнтвейта (индекс степени водного дефицита)', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_PETWettestQuarter':        {'title': 'ENVIREM: Среднемесячная потенциальная эвапотранспирация самого влажного квартала', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_PETWarmestQuarter':        {'title': 'ENVIREM: Среднемесячная потенциальная эвапотранспирация самого теплого квартала', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_PETseasonality':           {'title': 'ENVIREM: Сезонность потенциальной эвапотранспирации', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_annualPET':                {'title': 'ENVIREM: Годовая потенциальная эвапотранспирация', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_PETDriestQuarter':         {'title': 'ENVIREM: Среднемесячная потенциальная эвапотранспирация самого сухого квартала', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        'ENVIREM_PETColdestQuarter':        {'title': 'ENVIREM: Среднемесячная потенциальная эвапотранспирация холодного квартала', 'unit': '', 'scale': 1, 'diff': 0, 'min_val': 0},
        
        'SG_ocs_0-30cm_mean_1000':          {'title': 'SoilGrid: Запас органического углерода в почве на глубине 0-30 см', 'unit': 'кг/кв.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
    
        'SG_bdod_0-5cm_mean_1000':          {'title': 'SoilGrid: Плотность грунта на глубине 0-5 см', 'unit': 'кг/л', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_bdod_5-15cm_mean_1000':         {'title': 'SoilGrid: Плотность грунта на глубине 5-15 см', 'unit': 'кг/л', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_bdod_15-30cm_mean_1000':        {'title': 'SoilGrid: Плотность грунта на глубине 15-30 см', 'unit': 'кг/л', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_bdod_30-60cm_mean_1000':        {'title': 'SoilGrid: Плотность грунта на глубине 30-60 см', 'unit': 'кг/л', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_bdod_60-100cm_mean_1000':       {'title': 'SoilGrid: Плотность грунта на глубине 60-100 см', 'unit': 'кг/л', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_bdod_100-200cm_mean_1000':      {'title': 'SoilGrid: Плотность грунта на глубине 100-200 см', 'unit': 'кг/л', 'scale': 100, 'diff': 0, 'min_val': 0},
        
        'SG_cec_0-5cm_mean_1000':           {'title': 'SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 0-5 см', 'unit': 'смоль/кг', 'scale': 10, 'diff': 0, 'step': 1, 'min_val': 0},
        'SG_cec_5-15cm_mean_1000':          {'title': 'SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 5-15 см', 'unit': 'смоль/кг', 'scale': 10, 'diff': 0, 'step': 1, 'min_val': 0},
        'SG_cec_15-30cm_mean_1000':         {'title': 'SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 15-30 см', 'unit': 'смоль/кг', 'scale': 10, 'diff': 0, 'step': 1, 'min_val': 0},
        'SG_cec_30-60cm_mean_1000':         {'title': 'SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 30-60 см', 'unit': 'смоль/кг', 'scale': 10, 'diff': 0, 'step': 1, 'min_val': 0},
        'SG_cec_60-100cm_mean_1000':        {'title': 'SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 60-100 см', 'unit': 'смоль/кг', 'scale': 10, 'diff': 0, 'step': 1, 'min_val': 0},
        'SG_cec_100-200cm_mean_1000':       {'title': 'SoilGrid: Ёмкость катионного обмена почвы (ph=7) на глубине 100-200 см', 'unit': 'смоль/кг', 'scale': 10, 'diff': 0, 'step': 1, 'min_val': 0},
        
        'SG_cfvo_0-5cm_mean_1000':          {'title': 'SoilGrid: Объёмная доля крупных частиц на глубине 0-5 см', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_cfvo_5-15cm_mean_1000':         {'title': 'SoilGrid: Объёмная доля крупных частиц на глубине 5-15 см', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_cfvo_15-30cm_mean_1000':        {'title': 'SoilGrid: Объёмная доля крупных частиц на глубине 15-30 см', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_cfvo_30-60cm_mean_1000':        {'title': 'SoilGrid: Объёмная доля крупных частиц на глубине 30-60 см', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_cfvo_60-100cm_mean_1000':       {'title': 'SoilGrid: Объёмная доля крупных частиц на глубине 60-100 см', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        'SG_cfvo_100-200cm_mean_1000':      {'title': 'SoilGrid: Объёмная доля крупных частиц на глубине 100-200 см', 'unit': '%', 'scale': 100, 'diff': 0, 'min_val': 0},
        
        'SG_clay_0-5cm_mean_1000':          {'title': 'SoilGrid: Содержание глины в почве на глубине 0-5 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_clay_5-15cm_mean_1000':         {'title': 'SoilGrid: Содержание глины в почве на глубине 5-15 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_clay_15-30cm_mean_1000':        {'title': 'SoilGrid: Содержание глины в почве на глубине 15-30 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_clay_30-60cm_mean_1000':        {'title': 'SoilGrid: Содержание глины в почве на глубине 30-60 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_clay_60-100cm_mean_1000':       {'title': 'SoilGrid: Содержание глины в почве на глубине 60-100 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_clay_100-200cm_mean_1000':      {'title': 'SoilGrid: Содержание глины в почве на глубине 100-200 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'SG_nitrogen_0-5cm_mean_1000':      {'title': 'SoilGrid: Содержание азота в почве на глубине 0-5 см', 'unit': 'г/кг', 'scale': 100, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_nitrogen_5-15cm_mean_1000':     {'title': 'SoilGrid: Содержание азота в почве на глубине 5-15 см', 'unit': 'г/кг', 'scale': 100, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_nitrogen_15-30cm_mean_1000':    {'title': 'SoilGrid: Содержание азота в почве на глубине 15-30 см', 'unit': 'г/кг', 'scale': 100, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_nitrogen_30-60cm_mean_1000':    {'title': 'SoilGrid: Содержание азота в почве на глубине 30-60 см', 'unit': 'г/кг', 'scale': 100, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_nitrogen_60-100cm_mean_1000':   {'title': 'SoilGrid: Содержание азота в почве на глубине 60-100 см', 'unit': 'г/кг', 'scale': 100, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_nitrogen_100-200cm_mean_1000':  {'title': 'SoilGrid: Содержание азота в почве на глубине 100-200 см', 'unit': 'г/кг', 'scale': 100, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'SG_ocd_0-5cm_mean_1000':           {'title': 'SoilGrid: Плотность органического углерода в почве на глубине 0-5 см', 'unit': 'кг/куб.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_ocd_5-15cm_mean_1000':          {'title': 'SoilGrid: Плотность органического углерода в почве на глубине 5-15 см', 'unit': 'кг/куб.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_ocd_15-30cm_mean_1000':         {'title': 'SoilGrid: Плотность органического углерода в почве на глубине 15-30 см', 'unit': 'кг/куб.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_ocd_30-60cm_mean_1000':         {'title': 'SoilGrid: Плотность органического углерода в почве на глубине 30-60 см', 'unit': 'кг/куб.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_ocd_60-100cm_mean_1000':        {'title': 'SoilGrid: Плотность органического углерода в почве на глубине 60-100 см', 'unit': 'кг/куб.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_ocd_100-200cm_mean_1000':       {'title': 'SoilGrid: Плотность органического углерода в почве на глубине 100-200 см', 'unit': 'кг/куб.м', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'SG_soc_0-5cm_mean_1000':           {'title': 'SoilGrid: Почвенный органический углерод на глубине 0-5 см', 'unit': 'г/кг', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_soc_5-15cm_mean_1000':          {'title': 'SoilGrid: Почвенный органический углерод на глубине 5-15 см', 'unit': 'г/кг', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_soc_15-30cm_mean_1000':         {'title': 'SoilGrid: Почвенный органический углерод на глубине 15-30 см', 'unit': 'г/кг', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_soc_30-60cm_mean_1000':         {'title': 'SoilGrid: Почвенный органический углерод на глубине 30-60 см', 'unit': 'г/кг', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_soc_60-100cm_mean_1000':        {'title': 'SoilGrid: Почвенный органический углерод на глубине 60-100 см', 'unit': 'г/кг', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_soc_100-200cm_mean_1000':       {'title': 'SoilGrid: Почвенный органический углерод на глубине 100-200 см', 'unit': 'г/кг', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'SG_phh2o_0-5cm_mean_1000':         {'title': 'SoilGrid: pH воды на глубине 0-5 см', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0},
        'SG_phh2o_5-15cm_mean_1000':        {'title': 'SoilGrid: pH воды на глубине 5-15 см', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0},
        'SG_phh2o_15-30cm_mean_1000':       {'title': 'SoilGrid: pH воды на глубине 15-30 см', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0},
        'SG_phh2o_30-60cm_mean_1000':       {'title': 'SoilGrid: pH воды на глубине 30-60 см', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0},
        'SG_phh2o_60-100cm_mean_1000':      {'title': 'SoilGrid: pH воды на глубине 60-100 см', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0},
        'SG_phh2o_100-200cm_mean_1000':     {'title': 'SoilGrid: pH воды на глубине 100-200 см', 'unit': '', 'scale': 10, 'diff': 0, 'min_val': 0},
        
        'SG_sand_0-5cm_mean_1000':          {'title': 'SoilGrid: Содержание песка в почве на глубине 0-5 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_sand_5-15cm_mean_1000':         {'title': 'SoilGrid: Содержание песка в почве на глубине 5-15 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_sand_15-30cm_mean_1000':        {'title': 'SoilGrid: Содержание песка в почве на глубине 15-30 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_sand_30-60cm_mean_1000':        {'title': 'SoilGrid: Содержание песка в почве на глубине 30-60 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_sand_60-100cm_mean_1000':       {'title': 'SoilGrid: Содержание песка в почве на глубине 60-100 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_sand_100-200cm_mean_1000':      {'title': 'SoilGrid: Содержание песка в почве на глубине 100-200 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'SG_silt_0-5cm_mean_1000':          {'title': 'SoilGrid: Содержание илистых пород в почве на глубине 0-5 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_silt_5-15cm_mean_1000':         {'title': 'SoilGrid: Содержание илистых пород в почве на глубине 5-15 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_silt_15-30cm_mean_1000':        {'title': 'SoilGrid: Содержание илистых пород в почве на глубине 15-30 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_silt_30-60cm_mean_1000':        {'title': 'SoilGrid: Содержание илистых пород в почве на глубине 30-60 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_silt_60-100cm_mean_1000':       {'title': 'SoilGrid: Содержание илистых пород в почве на глубине 60-100 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_silt_100-200cm_mean_1000':      {'title': 'SoilGrid: Содержание илистых пород в почве на глубине 100-200 см', 'unit': 'г/100 г', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'SG_wv0010_0-5cm_mean_1000':        {'title': 'SoilGrid: Объемная влажность при 10 кПа на глубине 0-5 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0010_5-15cm_mean_1000':       {'title': 'SoilGrid: Объемная влажность при 10 кПа на глубине 5-15 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0010_15-30cm_mean_1000':      {'title': 'SoilGrid: Объемная влажность при 10 кПа на глубине 15-30 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0010_30-60cm_mean_1000':      {'title': 'SoilGrid: Объемная влажность при 10 кПа на глубине 30-60 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0010_60-100cm_mean_1000':     {'title': 'SoilGrid: Объемная влажность при 10 кПа на глубине 60-100 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0010_100-200cm_mean_1000':    {'title': 'SoilGrid: Объемная влажность при 10 кПа на глубине 100-200 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
    
        'SG_wv0033_0-5cm_mean_1000':        {'title': 'SoilGrid: Объемная влажность при 33 кПа на глубине 0-5 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0033_5-15cm_mean_1000':       {'title': 'SoilGrid: Объемная влажность при 33 кПа на глубине 5-15 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0033_15-30cm_mean_1000':      {'title': 'SoilGrid: Объемная влажность при 33 кПа на глубине 15-30 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0033_30-60cm_mean_1000':      {'title': 'SoilGrid: Объемная влажность при 33 кПа на глубине 30-60 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0033_60-100cm_mean_1000':     {'title': 'SoilGrid: Объемная влажность при 33 кПа на глубине 60-100 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv0033_100-200cm_mean_1000':    {'title': 'SoilGrid: Объемная влажность при 33 кПа на глубине 100-200 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        
        'SG_wv1500_0-5cm_mean_1000':        {'title': 'SoilGrid: Объемная влажность при 1500 кПа на глубине 0-5 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv1500_5-15cm_mean_1000':       {'title': 'SoilGrid: Объемная влажность при 1500 кПа на глубине 5-15 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv1500_15-30cm_mean_1000':      {'title': 'SoilGrid: Объемная влажность при 1500 кПа на глубине 15-30 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv1500_30-60cm_mean_1000':      {'title': 'SoilGrid: Объемная влажность при 1500 кПа на глубине 30-60 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv1500_60-100cm_mean_1000':     {'title': 'SoilGrid: Объемная влажность при 1500 кПа на глубине 60-100 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
        'SG_wv1500_100-200cm_mean_1000':    {'title': 'SoilGrid: Объемная влажность при 1500 кПа на глубине 100-200 см', 'unit': '%', 'scale': 10, 'diff': 0, 'min_val': 0, 'step': 1},
    }
    
    return bio_info